package com.application.entity;
// Generated Dec 16, 2019 3:13:56 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TArtikel generated by hbm2java
 */
public class TArtikel  implements java.io.Serializable {


     private Integer FIdArtikel;
     private String FLinkImg;
     private String FJudul;
     private String FKonten;
     private Date FTglKegiatan;

    public TArtikel() {
    }

    public TArtikel(String FLinkImg, String FJudul, String FKonten, Date FTglKegiatan) {
       this.FLinkImg = FLinkImg;
       this.FJudul = FJudul;
       this.FKonten = FKonten;
       this.FTglKegiatan = FTglKegiatan;
    }
   
    public Integer getFIdArtikel() {
        return this.FIdArtikel;
    }
    
    public void setFIdArtikel(Integer FIdArtikel) {
        this.FIdArtikel = FIdArtikel;
    }
    public String getFLinkImg() {
        return this.FLinkImg;
    }
    
    public void setFLinkImg(String FLinkImg) {
        this.FLinkImg = FLinkImg;
    }
    public String getFJudul() {
        return this.FJudul;
    }
    
    public void setFJudul(String FJudul) {
        this.FJudul = FJudul;
    }
    public String getFKonten() {
        return this.FKonten;
    }
    
    public void setFKonten(String FKonten) {
        this.FKonten = FKonten;
    }
    public Date getFTglKegiatan() {
        return this.FTglKegiatan;
    }
    
    public void setFTglKegiatan(Date FTglKegiatan) {
        this.FTglKegiatan = FTglKegiatan;
    }




}


