package com.application.entity;
// Generated Dec 16, 2019 3:13:56 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TFormulir generated by hbm2java
 */
public class TFormulir  implements java.io.Serializable {


     private Integer FIdForm;
     private int FIdLokasi;
     private int FKodedonor;
     private int FNoKtp;
     private String FNama;
     private String FAlamat;
     private String FKelurahan;
     private String FKecamatan;
     private int FKodepos;
     private String FJkelamin;
     private String FTempatLahir;
     private Date FTglLahir;
     private String FPekerjaan;
     private String FNamaibu;
     private String FStatusNikah;
     private String FGoldarah;
     private String FRhesus;
     private String FDipanggil;
     private int FNohp;

    public TFormulir() {
    }

    public TFormulir(int FIdLokasi, int FKodedonor, int FNoKtp, String FNama, String FAlamat, String FKelurahan, String FKecamatan, int FKodepos, String FJkelamin, String FTempatLahir, Date FTglLahir, String FPekerjaan, String FNamaibu, String FStatusNikah, String FGoldarah, String FRhesus, String FDipanggil, int FNohp) {
       this.FIdLokasi = FIdLokasi;
       this.FKodedonor = FKodedonor;
       this.FNoKtp = FNoKtp;
       this.FNama = FNama;
       this.FAlamat = FAlamat;
       this.FKelurahan = FKelurahan;
       this.FKecamatan = FKecamatan;
       this.FKodepos = FKodepos;
       this.FJkelamin = FJkelamin;
       this.FTempatLahir = FTempatLahir;
       this.FTglLahir = FTglLahir;
       this.FPekerjaan = FPekerjaan;
       this.FNamaibu = FNamaibu;
       this.FStatusNikah = FStatusNikah;
       this.FGoldarah = FGoldarah;
       this.FRhesus = FRhesus;
       this.FDipanggil = FDipanggil;
       this.FNohp = FNohp;
    }
   
    public Integer getFIdForm() {
        return this.FIdForm;
    }
    
    public void setFIdForm(Integer FIdForm) {
        this.FIdForm = FIdForm;
    }
    public int getFIdLokasi() {
        return this.FIdLokasi;
    }
    
    public void setFIdLokasi(int FIdLokasi) {
        this.FIdLokasi = FIdLokasi;
    }
    public int getFKodedonor() {
        return this.FKodedonor;
    }
    
    public void setFKodedonor(int FKodedonor) {
        this.FKodedonor = FKodedonor;
    }
    public int getFNoKtp() {
        return this.FNoKtp;
    }
    
    public void setFNoKtp(int FNoKtp) {
        this.FNoKtp = FNoKtp;
    }
    public String getFNama() {
        return this.FNama;
    }
    
    public void setFNama(String FNama) {
        this.FNama = FNama;
    }
    public String getFAlamat() {
        return this.FAlamat;
    }
    
    public void setFAlamat(String FAlamat) {
        this.FAlamat = FAlamat;
    }
    public String getFKelurahan() {
        return this.FKelurahan;
    }
    
    public void setFKelurahan(String FKelurahan) {
        this.FKelurahan = FKelurahan;
    }
    public String getFKecamatan() {
        return this.FKecamatan;
    }
    
    public void setFKecamatan(String FKecamatan) {
        this.FKecamatan = FKecamatan;
    }
    public int getFKodepos() {
        return this.FKodepos;
    }
    
    public void setFKodepos(int FKodepos) {
        this.FKodepos = FKodepos;
    }
    public String getFJkelamin() {
        return this.FJkelamin;
    }
    
    public void setFJkelamin(String FJkelamin) {
        this.FJkelamin = FJkelamin;
    }
    public String getFTempatLahir() {
        return this.FTempatLahir;
    }
    
    public void setFTempatLahir(String FTempatLahir) {
        this.FTempatLahir = FTempatLahir;
    }
    public Date getFTglLahir() {
        return this.FTglLahir;
    }
    
    public void setFTglLahir(Date FTglLahir) {
        this.FTglLahir = FTglLahir;
    }
    public String getFPekerjaan() {
        return this.FPekerjaan;
    }
    
    public void setFPekerjaan(String FPekerjaan) {
        this.FPekerjaan = FPekerjaan;
    }
    public String getFNamaibu() {
        return this.FNamaibu;
    }
    
    public void setFNamaibu(String FNamaibu) {
        this.FNamaibu = FNamaibu;
    }
    public String getFStatusNikah() {
        return this.FStatusNikah;
    }
    
    public void setFStatusNikah(String FStatusNikah) {
        this.FStatusNikah = FStatusNikah;
    }
    public String getFGoldarah() {
        return this.FGoldarah;
    }
    
    public void setFGoldarah(String FGoldarah) {
        this.FGoldarah = FGoldarah;
    }
    public String getFRhesus() {
        return this.FRhesus;
    }
    
    public void setFRhesus(String FRhesus) {
        this.FRhesus = FRhesus;
    }
    public String getFDipanggil() {
        return this.FDipanggil;
    }
    
    public void setFDipanggil(String FDipanggil) {
        this.FDipanggil = FDipanggil;
    }
    public int getFNohp() {
        return this.FNohp;
    }
    
    public void setFNohp(int FNohp) {
        this.FNohp = FNohp;
    }




}


