package com.application.entity;
// Generated Dec 16, 2019 3:13:56 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * THistori generated by hbm2java
 */
public class THistori  implements java.io.Serializable {


     private Integer FIdHadiah;
     private TStokDarah TStokDarah;
     private TUser TUser;
     private Date FTanggal;
     private int FDebitPoin;
     private int FKreditPoin;

    public THistori() {
    }

    public THistori(TStokDarah TStokDarah, TUser TUser, Date FTanggal, int FDebitPoin, int FKreditPoin) {
       this.TStokDarah = TStokDarah;
       this.TUser = TUser;
       this.FTanggal = FTanggal;
       this.FDebitPoin = FDebitPoin;
       this.FKreditPoin = FKreditPoin;
    }
   
    public Integer getFIdHadiah() {
        return this.FIdHadiah;
    }
    
    public void setFIdHadiah(Integer FIdHadiah) {
        this.FIdHadiah = FIdHadiah;
    }
    public TStokDarah getTStokDarah() {
        return this.TStokDarah;
    }
    
    public void setTStokDarah(TStokDarah TStokDarah) {
        this.TStokDarah = TStokDarah;
    }
    public TUser getTUser() {
        return this.TUser;
    }
    
    public void setTUser(TUser TUser) {
        this.TUser = TUser;
    }
    public Date getFTanggal() {
        return this.FTanggal;
    }
    
    public void setFTanggal(Date FTanggal) {
        this.FTanggal = FTanggal;
    }
    public int getFDebitPoin() {
        return this.FDebitPoin;
    }
    
    public void setFDebitPoin(int FDebitPoin) {
        this.FDebitPoin = FDebitPoin;
    }
    public int getFKreditPoin() {
        return this.FKreditPoin;
    }
    
    public void setFKreditPoin(int FKreditPoin) {
        this.FKreditPoin = FKreditPoin;
    }




}


