package com.application.entity;
// Generated Dec 16, 2019 3:13:56 PM by Hibernate Tools 4.3.1



/**
 * TLokasi generated by hbm2java
 */
public class TLokasi  implements java.io.Serializable {


     private int FIdLokasi;
     private String FNamaTempat;
     private int FIdProvinsi;
     private int FIdKota;
     private String FAlamat;
     private String FTlpn;
     private String FEmail;
     private byte FStatus;

    public TLokasi() {
    }

    public TLokasi(int FIdLokasi, String FNamaTempat, int FIdProvinsi, int FIdKota, String FAlamat, String FTlpn, String FEmail, byte FStatus) {
       this.FIdLokasi = FIdLokasi;
       this.FNamaTempat = FNamaTempat;
       this.FIdProvinsi = FIdProvinsi;
       this.FIdKota = FIdKota;
       this.FAlamat = FAlamat;
       this.FTlpn = FTlpn;
       this.FEmail = FEmail;
       this.FStatus = FStatus;
    }
   
    public int getFIdLokasi() {
        return this.FIdLokasi;
    }
    
    public void setFIdLokasi(int FIdLokasi) {
        this.FIdLokasi = FIdLokasi;
    }
    public String getFNamaTempat() {
        return this.FNamaTempat;
    }
    
    public void setFNamaTempat(String FNamaTempat) {
        this.FNamaTempat = FNamaTempat;
    }
    public int getFIdProvinsi() {
        return this.FIdProvinsi;
    }
    
    public void setFIdProvinsi(int FIdProvinsi) {
        this.FIdProvinsi = FIdProvinsi;
    }
    public int getFIdKota() {
        return this.FIdKota;
    }
    
    public void setFIdKota(int FIdKota) {
        this.FIdKota = FIdKota;
    }
    public String getFAlamat() {
        return this.FAlamat;
    }
    
    public void setFAlamat(String FAlamat) {
        this.FAlamat = FAlamat;
    }
    public String getFTlpn() {
        return this.FTlpn;
    }
    
    public void setFTlpn(String FTlpn) {
        this.FTlpn = FTlpn;
    }
    public String getFEmail() {
        return this.FEmail;
    }
    
    public void setFEmail(String FEmail) {
        this.FEmail = FEmail;
    }
    public byte getFStatus() {
        return this.FStatus;
    }
    
    public void setFStatus(byte FStatus) {
        this.FStatus = FStatus;
    }




}


