package com.application.entity;
// Generated Dec 16, 2019 3:13:56 PM by Hibernate Tools 4.3.1



/**
 * TProvinsi generated by hbm2java
 */
public class TProvinsi  implements java.io.Serializable {


     private Integer FIdProvinsi;
     private String FNamaProvinsi;

    public TProvinsi() {
    }

    public TProvinsi(String FNamaProvinsi) {
       this.FNamaProvinsi = FNamaProvinsi;
    }
   
    public Integer getFIdProvinsi() {
        return this.FIdProvinsi;
    }
    
    public void setFIdProvinsi(Integer FIdProvinsi) {
        this.FIdProvinsi = FIdProvinsi;
    }
    public String getFNamaProvinsi() {
        return this.FNamaProvinsi;
    }
    
    public void setFNamaProvinsi(String FNamaProvinsi) {
        this.FNamaProvinsi = FNamaProvinsi;
    }




}


